(library
 (name typed_endpoint_test)
 (package typed-endpoint-testing)
 (modules invariants json_schema_test)
 (libraries
  base
  jsonschema
  ppx_deriving_jsonschema.runtime
  typed-endpoint
  typed-endpoint-testing
  yojson)
 (inline_tests)
 (preprocess
  (pps ppx_let ppx_deriving_yojson ppx_deriving_jsonschema ppx_expect)))

(test
 (name property_test)
 (modules property_test)
 (package typed-endpoint-testing)
 (libraries base qcheck typed-endpoint typed-endpoint-testing uri))

(test
 (name compile_fail_test)
 (modules compile_fail_test)
 (package typed-endpoint-testing)
 (libraries base typed-endpoint typed-endpoint-testing unix)
 (deps
  compile_fail/valid.ml
  compile_fail/wrong_handler_arguments.ml
  compile_fail/wrong_payload.ml
  compile_fail/wrong_status.ml
  compile_fail/wrong_stage_order.ml)
 (action
  (run
   %{test}
   %{workspace_root}
   %{dep:compile_fail/valid.ml}
   %{dep:compile_fail/wrong_payload.ml}
   %{dep:compile_fail/wrong_status.ml}
   %{dep:compile_fail/wrong_handler_arguments.ml}
   %{dep:compile_fail/wrong_stage_order.ml})))
