(library
 (name typed_endpoint_test)
 (package typed-endpoint-testing)
 (modules invariants)
 (libraries
  base
  cohttp
  ppx_deriving_jsonschema.runtime
  typed-endpoint
  typed-endpoint-testing
  yojson)
 (inline_tests)
 (preprocess
  (pps ppx_let ppx_deriving_yojson ppx_deriving_jsonschema ppx_expect)))
