(library
 (name typed_endpoint_test)
 (package typed-endpoint-opium)
 (modules invariants routes)
 (libraries
  base
  cohttp
  lwt
  opium
  ppx_deriving_jsonschema.runtime
  typed-endpoint
  typed-endpoint-opium
  yojson)
 (inline_tests)
 (preprocess
  (pps ppx_let ppx_deriving_yojson ppx_deriving_jsonschema ppx_expect)))

(executable
 (name app)
 (modules app)
 (libraries base cohttp lwt.unix opium typed_endpoint_test yojson))
