(include_subdirs unqualified)

(library
 (name petstore_app)
 (modules
  domain
  persistence_error
  database
  dto
  pet_repository
  order_repository
  user_repository
  database_memory
  pet_service
  order_service
  user_service
  auth
  api_docs
  http_parameter
  controller_context
  pet_controller
  store_controller
  user_controller
  routes)
 (private_modules api_docs)
 (libraries base ppx_deriving_jsonschema.runtime typed-endpoint yojson)
 (preprocess
  (pps ppx_let ppx_deriving_yojson ppx_deriving_jsonschema)))
