open! Base

(** An abstract JSON Schema fragment. Values are independent of OpenAPI
    component names and can be used inline by parameters, headers, bodies, and
    responses. *)
type t

(** Standard JSON Schema and OpenAPI string formats. [`Custom name] preserves
    extensibility while making all built-in choices typo-safe. *)
type string_format =
  [ `Binary
  | `Byte
  | `Date
  | `Date_time
  | `Duration
  | `Email
  | `Hostname
  | `Idn_email
  | `Idn_hostname
  | `Ipv4
  | `Ipv6
  | `Iri
  | `Iri_reference
  | `Json_pointer
  | `Password
  | `Regex
  | `Relative_json_pointer
  | `Time
  | `Uri
  | `Uri_reference
  | `Uri_template
  | `Uuid
  | `Custom of string
  ]

(** Standard OpenAPI integer formats. *)
type integer_format =
  [ `Int32
  | `Int64
  | `Custom of string
  ]

(** Standard OpenAPI number formats. *)
type number_format =
  [ `Double
  | `Float
  | `Custom of string
  ]

(** A schema accepting every JSON value. *)
val any : t

(** A schema accepting only JSON [null]. *)
val null : t

(** Structural equality that ignores object-member order and preserves array
    order. *)
val equal : t -> t -> bool

(** Returns the JSON representation used by OpenAPI rendering. *)
val to_yojson : t -> Yojson.Safe.t

(** Imports a schema generated by [ppx_deriving_jsonschema]. *)
val of_ppx : Ppx_deriving_jsonschema_runtime.t -> t

(** Exports a schema for a custom type consumed by
    [ppx_deriving_jsonschema]. *)
val to_ppx : t -> Ppx_deriving_jsonschema_runtime.t

(** Builds a string schema. A [`Custom format] must be non-empty, lengths must
    be non-negative and ordered, [enum] must be non-empty without duplicates,
    and [default] must belong to [enum] when both are present. *)
val string
  :  ?format:string_format
  -> ?enum:string list
  -> ?min_length:int
  -> ?max_length:int
  -> ?default:string
  -> unit
  -> (t, string) Result.t

(** The throwing form of {!string}. Invalid arguments raise [Invalid_argument]. *)
val string_exn
  :  ?format:string_format
  -> ?enum:string list
  -> ?min_length:int
  -> ?max_length:int
  -> ?default:string
  -> unit
  -> t

(** Builds an integer schema. A [`Custom format] must be non-empty, bounds must
    be ordered, and [default] must fall within them. *)
val integer
  :  ?format:integer_format
  -> ?minimum:int
  -> ?maximum:int
  -> ?default:int
  -> unit
  -> (t, string) Result.t

(** The throwing form of {!integer}. Invalid arguments raise
    [Invalid_argument]. *)
val integer_exn
  :  ?format:integer_format
  -> ?minimum:int
  -> ?maximum:int
  -> ?default:int
  -> unit
  -> t

(** Builds a number schema. A [`Custom format] must be non-empty. Bounds and
    [default] must be finite and ordered, and [default] must fall within them. *)
val number
  :  ?format:number_format
  -> ?minimum:float
  -> ?maximum:float
  -> ?default:float
  -> unit
  -> (t, string) Result.t

(** The throwing form of {!number}. Invalid arguments raise [Invalid_argument]. *)
val number_exn
  :  ?format:number_format
  -> ?minimum:float
  -> ?maximum:float
  -> ?default:float
  -> unit
  -> t

(** Builds a boolean schema with an optional documented default. *)
val boolean : ?default:bool -> unit -> t

(** Builds an array schema. Item bounds must be non-negative and ordered. *)
val array : ?min_items:int -> ?max_items:int -> items:t -> unit -> (t, string) Result.t

(** The throwing form of {!array}. Invalid arguments raise [Invalid_argument]. *)
val array_exn : ?min_items:int -> ?max_items:int -> items:t -> unit -> t

(** An object whose arbitrary property values conform to [values]. *)
val dictionary : values:t -> t

(** Allows JSON [null] in addition to [schema]. Applying [nullable] more than
    once has no further effect. *)
val nullable : t -> t

module Unsafe : sig
  (** Imports an unchecked JSON value. Use only for JSON Schema keywords not
      represented by the safe constructors. An [`Intlit] must fit into an OCaml
      [int], otherwise this function raises [Invalid_argument]. *)
  val of_yojson : Yojson.Safe.t -> t
end
